//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusSystem.JavaBusService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autobusy.kniedzwiecki.eu/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autobusy.kniedzwiecki.eu/")]
    public partial class stop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private bool onDemandField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool onDemand {
            get {
                return this.onDemandField;
            }
            set {
                this.onDemandField = value;
                this.RaisePropertyChanged("onDemand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autobusy.kniedzwiecki.eu/")]
    public partial class connection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int aField;
        
        private int bField;
        
        private int timeABField;
        
        private int timeBAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int a {
            get {
                return this.aField;
            }
            set {
                this.aField = value;
                this.RaisePropertyChanged("a");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int b {
            get {
                return this.bField;
            }
            set {
                this.bField = value;
                this.RaisePropertyChanged("b");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int timeAB {
            get {
                return this.timeABField;
            }
            set {
                this.timeABField = value;
                this.RaisePropertyChanged("timeAB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int timeBA {
            get {
                return this.timeBAField;
            }
            set {
                this.timeBAField = value;
                this.RaisePropertyChanged("timeBA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autobusy.kniedzwiecki.eu/")]
    public partial class line : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private connection[] stopsField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public connection[] stops {
            get {
                return this.stopsField;
            }
            set {
                this.stopsField = value;
                this.RaisePropertyChanged("stops");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autobusy.kniedzwiecki.eu/")]
    public partial class driver : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autobusy.kniedzwiecki.eu/")]
    public partial class bus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string brandField;
        
        private string modelField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("brand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autobusy.kniedzwiecki.eu/")]
    public partial class dataBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bus[] busesField;
        
        private driver[] driversField;
        
        private line[] linesField;
        
        private stop[] stopsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public bus[] buses {
            get {
                return this.busesField;
            }
            set {
                this.busesField = value;
                this.RaisePropertyChanged("buses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public driver[] drivers {
            get {
                return this.driversField;
            }
            set {
                this.driversField = value;
                this.RaisePropertyChanged("drivers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public line[] lines {
            get {
                return this.linesField;
            }
            set {
                this.linesField = value;
                this.RaisePropertyChanged("lines");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public stop[] stops {
            get {
                return this.stopsField;
            }
            set {
                this.stopsField = value;
                this.RaisePropertyChanged("stops");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="DataBase", Namespace="http://autobusy.kniedzwiecki.eu/", ConfigurationName="JavaBusService.DataBase1")]
    public interface DataBase1 {
        
        // CODEGEN: Parameter 'database' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/getDatabaseContentsRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/getDatabaseContentsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="database")]
        BusSystem.JavaBusService.getDatabaseContentsResponse getDatabaseContents(BusSystem.JavaBusService.getDatabaseContentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/getDatabaseContentsRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/getDatabaseContentsResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.getDatabaseContentsResponse> getDatabaseContentsAsync(BusSystem.JavaBusService.getDatabaseContentsRequest request);
        
        // CODEGEN: Parameter 'line' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/findLineByIdRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/findLineByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="line")]
        BusSystem.JavaBusService.findLineByIdResponse findLineById(BusSystem.JavaBusService.findLineByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/findLineByIdRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/findLineByIdResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.findLineByIdResponse> findLineByIdAsync(BusSystem.JavaBusService.findLineByIdRequest request);
        
        // CODEGEN: Parameter 'driver' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/findDriverByIdRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/findDriverByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="driver")]
        BusSystem.JavaBusService.findDriverByIdResponse findDriverById(BusSystem.JavaBusService.findDriverByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/findDriverByIdRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/findDriverByIdResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.findDriverByIdResponse> findDriverByIdAsync(BusSystem.JavaBusService.findDriverByIdRequest request);
        
        // CODEGEN: Parameter 'bus' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/findBusByIdRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/findBusByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="bus")]
        BusSystem.JavaBusService.findBusByIdResponse findBusById(BusSystem.JavaBusService.findBusByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/findBusByIdRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/findBusByIdResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.findBusByIdResponse> findBusByIdAsync(BusSystem.JavaBusService.findBusByIdRequest request);
        
        // CODEGEN: Parameter 'stops' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/setStopsRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/setStopsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        BusSystem.JavaBusService.setStopsResponse setStops(BusSystem.JavaBusService.setStopsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/setStopsRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/setStopsResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.setStopsResponse> setStopsAsync(BusSystem.JavaBusService.setStopsRequest request);
        
        // CODEGEN: Parameter 'driver' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/getDriversRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/getDriversResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="driver")]
        BusSystem.JavaBusService.getDriversResponse getDrivers(BusSystem.JavaBusService.getDriversRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/getDriversRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/getDriversResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.getDriversResponse> getDriversAsync(BusSystem.JavaBusService.getDriversRequest request);
        
        // CODEGEN: Parameter 'drivers' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/setDriversRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/setDriversResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        BusSystem.JavaBusService.setDriversResponse setDrivers(BusSystem.JavaBusService.setDriversRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/setDriversRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/setDriversResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.setDriversResponse> setDriversAsync(BusSystem.JavaBusService.setDriversRequest request);
        
        // CODEGEN: Parameter 'runID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/createRunRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/createRunResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BusSystem.JavaBusService.Exception), Action="http://autobusy.kniedzwiecki.eu/DataBase/createRun/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="runID")]
        BusSystem.JavaBusService.createRunResponse createRun(BusSystem.JavaBusService.createRunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/createRunRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/createRunResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.createRunResponse> createRunAsync(BusSystem.JavaBusService.createRunRequest request);
        
        // CODEGEN: Parameter 'line' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/getLinesRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/getLinesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="line")]
        BusSystem.JavaBusService.getLinesResponse getLines(BusSystem.JavaBusService.getLinesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/getLinesRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/getLinesResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.getLinesResponse> getLinesAsync(BusSystem.JavaBusService.getLinesRequest request);
        
        // CODEGEN: Parameter 'buses' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/setBusesRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/setBusesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        BusSystem.JavaBusService.setBusesResponse setBuses(BusSystem.JavaBusService.setBusesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/setBusesRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/setBusesResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.setBusesResponse> setBusesAsync(BusSystem.JavaBusService.setBusesRequest request);
        
        // CODEGEN: Parameter 'bus' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/getBusesRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/getBusesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="bus")]
        BusSystem.JavaBusService.getBusesResponse getBuses(BusSystem.JavaBusService.getBusesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/getBusesRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/getBusesResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.getBusesResponse> getBusesAsync(BusSystem.JavaBusService.getBusesRequest request);
        
        // CODEGEN: Parameter 'stop' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/findStopByIdRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/findStopByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="stop")]
        BusSystem.JavaBusService.findStopByIdResponse findStopById(BusSystem.JavaBusService.findStopByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/findStopByIdRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/findStopByIdResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.findStopByIdResponse> findStopByIdAsync(BusSystem.JavaBusService.findStopByIdRequest request);
        
        // CODEGEN: Parameter 'stop' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/getStopsRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/getStopsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="stop")]
        BusSystem.JavaBusService.getStopsResponse getStops(BusSystem.JavaBusService.getStopsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/getStopsRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/getStopsResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.getStopsResponse> getStopsAsync(BusSystem.JavaBusService.getStopsRequest request);
        
        // CODEGEN: Parameter 'results' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/getStopResultsRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/getStopResultsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BusSystem.JavaBusService.Exception), Action="http://autobusy.kniedzwiecki.eu/DataBase/getStopResults/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="results")]
        BusSystem.JavaBusService.getStopResultsResponse getStopResults(BusSystem.JavaBusService.getStopResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/getStopResultsRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/getStopResultsResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.getStopResultsResponse> getStopResultsAsync(BusSystem.JavaBusService.getStopResultsRequest request);
        
        // CODEGEN: Parameter 'incremented' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/incrementRunStopRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/incrementRunStopResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BusSystem.JavaBusService.Exception), Action="http://autobusy.kniedzwiecki.eu/DataBase/incrementRunStop/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="incremented")]
        BusSystem.JavaBusService.incrementRunStopResponse incrementRunStop(BusSystem.JavaBusService.incrementRunStopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/incrementRunStopRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/incrementRunStopResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.incrementRunStopResponse> incrementRunStopAsync(BusSystem.JavaBusService.incrementRunStopRequest request);
        
        // CODEGEN: Parameter 'lines' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/setLinesRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/setLinesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(driver[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(connection[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(line[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stop[]))]
        BusSystem.JavaBusService.setLinesResponse setLines(BusSystem.JavaBusService.setLinesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autobusy.kniedzwiecki.eu/DataBase/setLinesRequest", ReplyAction="http://autobusy.kniedzwiecki.eu/DataBase/setLinesResponse")]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.setLinesResponse> setLinesAsync(BusSystem.JavaBusService.setLinesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDatabaseContents", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getDatabaseContentsRequest {
        
        public getDatabaseContentsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDatabaseContentsResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getDatabaseContentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.dataBase database;
        
        public getDatabaseContentsResponse() {
        }
        
        public getDatabaseContentsResponse(BusSystem.JavaBusService.dataBase database) {
            this.database = database;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findLineById", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class findLineByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int lineID;
        
        public findLineByIdRequest() {
        }
        
        public findLineByIdRequest(int lineID) {
            this.lineID = lineID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findLineByIdResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class findLineByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.line line;
        
        public findLineByIdResponse() {
        }
        
        public findLineByIdResponse(BusSystem.JavaBusService.line line) {
            this.line = line;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findDriverById", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class findDriverByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int driverID;
        
        public findDriverByIdRequest() {
        }
        
        public findDriverByIdRequest(int driverID) {
            this.driverID = driverID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findDriverByIdResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class findDriverByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.driver driver;
        
        public findDriverByIdResponse() {
        }
        
        public findDriverByIdResponse(BusSystem.JavaBusService.driver driver) {
            this.driver = driver;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findBusById", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class findBusByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int busID;
        
        public findBusByIdRequest() {
        }
        
        public findBusByIdRequest(int busID) {
            this.busID = busID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findBusByIdResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class findBusByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.bus bus;
        
        public findBusByIdResponse() {
        }
        
        public findBusByIdResponse(BusSystem.JavaBusService.bus bus) {
            this.bus = bus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setStops", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class setStopsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("stops", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.stop[] stops;
        
        public setStopsRequest() {
        }
        
        public setStopsRequest(BusSystem.JavaBusService.stop[] stops) {
            this.stops = stops;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setStopsResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class setStopsResponse {
        
        public setStopsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDrivers", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getDriversRequest {
        
        public getDriversRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDriversResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getDriversResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("driver", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.driver[] driver;
        
        public getDriversResponse() {
        }
        
        public getDriversResponse(BusSystem.JavaBusService.driver[] driver) {
            this.driver = driver;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDrivers", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class setDriversRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("drivers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.driver[] drivers;
        
        public setDriversRequest() {
        }
        
        public setDriversRequest(BusSystem.JavaBusService.driver[] drivers) {
            this.drivers = drivers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDriversResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class setDriversResponse {
        
        public setDriversResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createRun", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class createRunRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int driverID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int busID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int lineID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isDirectionAB;
        
        public createRunRequest() {
        }
        
        public createRunRequest(int driverID, int busID, int lineID, bool isDirectionAB) {
            this.driverID = driverID;
            this.busID = busID;
            this.lineID = lineID;
            this.isDirectionAB = isDirectionAB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createRunResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class createRunResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int runID;
        
        public createRunResponse() {
        }
        
        public createRunResponse(int runID) {
            this.runID = runID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLines", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getLinesRequest {
        
        public getLinesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLinesResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getLinesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("line", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.line[] line;
        
        public getLinesResponse() {
        }
        
        public getLinesResponse(BusSystem.JavaBusService.line[] line) {
            this.line = line;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setBuses", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class setBusesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("buses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.bus[] buses;
        
        public setBusesRequest() {
        }
        
        public setBusesRequest(BusSystem.JavaBusService.bus[] buses) {
            this.buses = buses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setBusesResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class setBusesResponse {
        
        public setBusesResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBuses", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getBusesRequest {
        
        public getBusesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBusesResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getBusesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("bus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.bus[] bus;
        
        public getBusesResponse() {
        }
        
        public getBusesResponse(BusSystem.JavaBusService.bus[] bus) {
            this.bus = bus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findStopById", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class findStopByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stopID;
        
        public findStopByIdRequest() {
        }
        
        public findStopByIdRequest(int stopID) {
            this.stopID = stopID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findStopByIdResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class findStopByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.stop stop;
        
        public findStopByIdResponse() {
        }
        
        public findStopByIdResponse(BusSystem.JavaBusService.stop stop) {
            this.stop = stop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStops", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getStopsRequest {
        
        public getStopsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStopsResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getStopsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("stop", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.stop[] stop;
        
        public getStopsResponse() {
        }
        
        public getStopsResponse(BusSystem.JavaBusService.stop[] stop) {
            this.stop = stop;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autobusy.kniedzwiecki.eu/")]
    public partial class busStopSearchResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lineField;
        
        private string destinationField;
        
        private int arrivesInField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
                this.RaisePropertyChanged("Line");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("Destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int ArrivesIn {
            get {
                return this.arrivesInField;
            }
            set {
                this.arrivesInField = value;
                this.RaisePropertyChanged("ArrivesIn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStopResults", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getStopResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stopID;
        
        public getStopResultsRequest() {
        }
        
        public getStopResultsRequest(int stopID) {
            this.stopID = stopID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStopResultsResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getStopResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("results", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.busStopSearchResult[] results;
        
        public getStopResultsResponse() {
        }
        
        public getStopResultsResponse(BusSystem.JavaBusService.busStopSearchResult[] results) {
            this.results = results;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="incrementRunStop", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class incrementRunStopRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int runID;
        
        public incrementRunStopRequest() {
        }
        
        public incrementRunStopRequest(int runID) {
            this.runID = runID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="incrementRunStopResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class incrementRunStopResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool incremented;
        
        public incrementRunStopResponse() {
        }
        
        public incrementRunStopResponse(bool incremented) {
            this.incremented = incremented;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setLines", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class setLinesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autobusy.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusSystem.JavaBusService.line[] lines;
        
        public setLinesRequest() {
        }
        
        public setLinesRequest(BusSystem.JavaBusService.line[] lines) {
            this.lines = lines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setLinesResponse", WrapperNamespace="http://autobusy.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class setLinesResponse {
        
        public setLinesResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataBase1Channel : BusSystem.JavaBusService.DataBase1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataBase1Client : System.ServiceModel.ClientBase<BusSystem.JavaBusService.DataBase1>, BusSystem.JavaBusService.DataBase1 {
        
        public DataBase1Client() {
        }
        
        public DataBase1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataBase1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBase1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBase1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.getDatabaseContentsResponse BusSystem.JavaBusService.DataBase1.getDatabaseContents(BusSystem.JavaBusService.getDatabaseContentsRequest request) {
            return base.Channel.getDatabaseContents(request);
        }
        
        public BusSystem.JavaBusService.dataBase getDatabaseContents() {
            BusSystem.JavaBusService.getDatabaseContentsRequest inValue = new BusSystem.JavaBusService.getDatabaseContentsRequest();
            BusSystem.JavaBusService.getDatabaseContentsResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).getDatabaseContents(inValue);
            return retVal.database;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.getDatabaseContentsResponse> BusSystem.JavaBusService.DataBase1.getDatabaseContentsAsync(BusSystem.JavaBusService.getDatabaseContentsRequest request) {
            return base.Channel.getDatabaseContentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.getDatabaseContentsResponse> getDatabaseContentsAsync() {
            BusSystem.JavaBusService.getDatabaseContentsRequest inValue = new BusSystem.JavaBusService.getDatabaseContentsRequest();
            return ((BusSystem.JavaBusService.DataBase1)(this)).getDatabaseContentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.findLineByIdResponse BusSystem.JavaBusService.DataBase1.findLineById(BusSystem.JavaBusService.findLineByIdRequest request) {
            return base.Channel.findLineById(request);
        }
        
        public BusSystem.JavaBusService.line findLineById(int lineID) {
            BusSystem.JavaBusService.findLineByIdRequest inValue = new BusSystem.JavaBusService.findLineByIdRequest();
            inValue.lineID = lineID;
            BusSystem.JavaBusService.findLineByIdResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).findLineById(inValue);
            return retVal.line;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.findLineByIdResponse> BusSystem.JavaBusService.DataBase1.findLineByIdAsync(BusSystem.JavaBusService.findLineByIdRequest request) {
            return base.Channel.findLineByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.findLineByIdResponse> findLineByIdAsync(int lineID) {
            BusSystem.JavaBusService.findLineByIdRequest inValue = new BusSystem.JavaBusService.findLineByIdRequest();
            inValue.lineID = lineID;
            return ((BusSystem.JavaBusService.DataBase1)(this)).findLineByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.findDriverByIdResponse BusSystem.JavaBusService.DataBase1.findDriverById(BusSystem.JavaBusService.findDriverByIdRequest request) {
            return base.Channel.findDriverById(request);
        }
        
        public BusSystem.JavaBusService.driver findDriverById(int driverID) {
            BusSystem.JavaBusService.findDriverByIdRequest inValue = new BusSystem.JavaBusService.findDriverByIdRequest();
            inValue.driverID = driverID;
            BusSystem.JavaBusService.findDriverByIdResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).findDriverById(inValue);
            return retVal.driver;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.findDriverByIdResponse> BusSystem.JavaBusService.DataBase1.findDriverByIdAsync(BusSystem.JavaBusService.findDriverByIdRequest request) {
            return base.Channel.findDriverByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.findDriverByIdResponse> findDriverByIdAsync(int driverID) {
            BusSystem.JavaBusService.findDriverByIdRequest inValue = new BusSystem.JavaBusService.findDriverByIdRequest();
            inValue.driverID = driverID;
            return ((BusSystem.JavaBusService.DataBase1)(this)).findDriverByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.findBusByIdResponse BusSystem.JavaBusService.DataBase1.findBusById(BusSystem.JavaBusService.findBusByIdRequest request) {
            return base.Channel.findBusById(request);
        }
        
        public BusSystem.JavaBusService.bus findBusById(int busID) {
            BusSystem.JavaBusService.findBusByIdRequest inValue = new BusSystem.JavaBusService.findBusByIdRequest();
            inValue.busID = busID;
            BusSystem.JavaBusService.findBusByIdResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).findBusById(inValue);
            return retVal.bus;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.findBusByIdResponse> BusSystem.JavaBusService.DataBase1.findBusByIdAsync(BusSystem.JavaBusService.findBusByIdRequest request) {
            return base.Channel.findBusByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.findBusByIdResponse> findBusByIdAsync(int busID) {
            BusSystem.JavaBusService.findBusByIdRequest inValue = new BusSystem.JavaBusService.findBusByIdRequest();
            inValue.busID = busID;
            return ((BusSystem.JavaBusService.DataBase1)(this)).findBusByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.setStopsResponse BusSystem.JavaBusService.DataBase1.setStops(BusSystem.JavaBusService.setStopsRequest request) {
            return base.Channel.setStops(request);
        }
        
        public void setStops(BusSystem.JavaBusService.stop[] stops) {
            BusSystem.JavaBusService.setStopsRequest inValue = new BusSystem.JavaBusService.setStopsRequest();
            inValue.stops = stops;
            BusSystem.JavaBusService.setStopsResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).setStops(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.setStopsResponse> BusSystem.JavaBusService.DataBase1.setStopsAsync(BusSystem.JavaBusService.setStopsRequest request) {
            return base.Channel.setStopsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.setStopsResponse> setStopsAsync(BusSystem.JavaBusService.stop[] stops) {
            BusSystem.JavaBusService.setStopsRequest inValue = new BusSystem.JavaBusService.setStopsRequest();
            inValue.stops = stops;
            return ((BusSystem.JavaBusService.DataBase1)(this)).setStopsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.getDriversResponse BusSystem.JavaBusService.DataBase1.getDrivers(BusSystem.JavaBusService.getDriversRequest request) {
            return base.Channel.getDrivers(request);
        }
        
        public BusSystem.JavaBusService.driver[] getDrivers() {
            BusSystem.JavaBusService.getDriversRequest inValue = new BusSystem.JavaBusService.getDriversRequest();
            BusSystem.JavaBusService.getDriversResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).getDrivers(inValue);
            return retVal.driver;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.getDriversResponse> BusSystem.JavaBusService.DataBase1.getDriversAsync(BusSystem.JavaBusService.getDriversRequest request) {
            return base.Channel.getDriversAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.getDriversResponse> getDriversAsync() {
            BusSystem.JavaBusService.getDriversRequest inValue = new BusSystem.JavaBusService.getDriversRequest();
            return ((BusSystem.JavaBusService.DataBase1)(this)).getDriversAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.setDriversResponse BusSystem.JavaBusService.DataBase1.setDrivers(BusSystem.JavaBusService.setDriversRequest request) {
            return base.Channel.setDrivers(request);
        }
        
        public void setDrivers(BusSystem.JavaBusService.driver[] drivers) {
            BusSystem.JavaBusService.setDriversRequest inValue = new BusSystem.JavaBusService.setDriversRequest();
            inValue.drivers = drivers;
            BusSystem.JavaBusService.setDriversResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).setDrivers(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.setDriversResponse> BusSystem.JavaBusService.DataBase1.setDriversAsync(BusSystem.JavaBusService.setDriversRequest request) {
            return base.Channel.setDriversAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.setDriversResponse> setDriversAsync(BusSystem.JavaBusService.driver[] drivers) {
            BusSystem.JavaBusService.setDriversRequest inValue = new BusSystem.JavaBusService.setDriversRequest();
            inValue.drivers = drivers;
            return ((BusSystem.JavaBusService.DataBase1)(this)).setDriversAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.createRunResponse BusSystem.JavaBusService.DataBase1.createRun(BusSystem.JavaBusService.createRunRequest request) {
            return base.Channel.createRun(request);
        }
        
        public int createRun(int driverID, int busID, int lineID, bool isDirectionAB) {
            BusSystem.JavaBusService.createRunRequest inValue = new BusSystem.JavaBusService.createRunRequest();
            inValue.driverID = driverID;
            inValue.busID = busID;
            inValue.lineID = lineID;
            inValue.isDirectionAB = isDirectionAB;
            BusSystem.JavaBusService.createRunResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).createRun(inValue);
            return retVal.runID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.createRunResponse> BusSystem.JavaBusService.DataBase1.createRunAsync(BusSystem.JavaBusService.createRunRequest request) {
            return base.Channel.createRunAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.createRunResponse> createRunAsync(int driverID, int busID, int lineID, bool isDirectionAB) {
            BusSystem.JavaBusService.createRunRequest inValue = new BusSystem.JavaBusService.createRunRequest();
            inValue.driverID = driverID;
            inValue.busID = busID;
            inValue.lineID = lineID;
            inValue.isDirectionAB = isDirectionAB;
            return ((BusSystem.JavaBusService.DataBase1)(this)).createRunAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.getLinesResponse BusSystem.JavaBusService.DataBase1.getLines(BusSystem.JavaBusService.getLinesRequest request) {
            return base.Channel.getLines(request);
        }
        
        public BusSystem.JavaBusService.line[] getLines() {
            BusSystem.JavaBusService.getLinesRequest inValue = new BusSystem.JavaBusService.getLinesRequest();
            BusSystem.JavaBusService.getLinesResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).getLines(inValue);
            return retVal.line;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.getLinesResponse> BusSystem.JavaBusService.DataBase1.getLinesAsync(BusSystem.JavaBusService.getLinesRequest request) {
            return base.Channel.getLinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.getLinesResponse> getLinesAsync() {
            BusSystem.JavaBusService.getLinesRequest inValue = new BusSystem.JavaBusService.getLinesRequest();
            return ((BusSystem.JavaBusService.DataBase1)(this)).getLinesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.setBusesResponse BusSystem.JavaBusService.DataBase1.setBuses(BusSystem.JavaBusService.setBusesRequest request) {
            return base.Channel.setBuses(request);
        }
        
        public void setBuses(BusSystem.JavaBusService.bus[] buses) {
            BusSystem.JavaBusService.setBusesRequest inValue = new BusSystem.JavaBusService.setBusesRequest();
            inValue.buses = buses;
            BusSystem.JavaBusService.setBusesResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).setBuses(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.setBusesResponse> BusSystem.JavaBusService.DataBase1.setBusesAsync(BusSystem.JavaBusService.setBusesRequest request) {
            return base.Channel.setBusesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.setBusesResponse> setBusesAsync(BusSystem.JavaBusService.bus[] buses) {
            BusSystem.JavaBusService.setBusesRequest inValue = new BusSystem.JavaBusService.setBusesRequest();
            inValue.buses = buses;
            return ((BusSystem.JavaBusService.DataBase1)(this)).setBusesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.getBusesResponse BusSystem.JavaBusService.DataBase1.getBuses(BusSystem.JavaBusService.getBusesRequest request) {
            return base.Channel.getBuses(request);
        }
        
        public BusSystem.JavaBusService.bus[] getBuses() {
            BusSystem.JavaBusService.getBusesRequest inValue = new BusSystem.JavaBusService.getBusesRequest();
            BusSystem.JavaBusService.getBusesResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).getBuses(inValue);
            return retVal.bus;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.getBusesResponse> BusSystem.JavaBusService.DataBase1.getBusesAsync(BusSystem.JavaBusService.getBusesRequest request) {
            return base.Channel.getBusesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.getBusesResponse> getBusesAsync() {
            BusSystem.JavaBusService.getBusesRequest inValue = new BusSystem.JavaBusService.getBusesRequest();
            return ((BusSystem.JavaBusService.DataBase1)(this)).getBusesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.findStopByIdResponse BusSystem.JavaBusService.DataBase1.findStopById(BusSystem.JavaBusService.findStopByIdRequest request) {
            return base.Channel.findStopById(request);
        }
        
        public BusSystem.JavaBusService.stop findStopById(int stopID) {
            BusSystem.JavaBusService.findStopByIdRequest inValue = new BusSystem.JavaBusService.findStopByIdRequest();
            inValue.stopID = stopID;
            BusSystem.JavaBusService.findStopByIdResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).findStopById(inValue);
            return retVal.stop;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.findStopByIdResponse> BusSystem.JavaBusService.DataBase1.findStopByIdAsync(BusSystem.JavaBusService.findStopByIdRequest request) {
            return base.Channel.findStopByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.findStopByIdResponse> findStopByIdAsync(int stopID) {
            BusSystem.JavaBusService.findStopByIdRequest inValue = new BusSystem.JavaBusService.findStopByIdRequest();
            inValue.stopID = stopID;
            return ((BusSystem.JavaBusService.DataBase1)(this)).findStopByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.getStopsResponse BusSystem.JavaBusService.DataBase1.getStops(BusSystem.JavaBusService.getStopsRequest request) {
            return base.Channel.getStops(request);
        }
        
        public BusSystem.JavaBusService.stop[] getStops() {
            BusSystem.JavaBusService.getStopsRequest inValue = new BusSystem.JavaBusService.getStopsRequest();
            BusSystem.JavaBusService.getStopsResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).getStops(inValue);
            return retVal.stop;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.getStopsResponse> BusSystem.JavaBusService.DataBase1.getStopsAsync(BusSystem.JavaBusService.getStopsRequest request) {
            return base.Channel.getStopsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.getStopsResponse> getStopsAsync() {
            BusSystem.JavaBusService.getStopsRequest inValue = new BusSystem.JavaBusService.getStopsRequest();
            return ((BusSystem.JavaBusService.DataBase1)(this)).getStopsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.getStopResultsResponse BusSystem.JavaBusService.DataBase1.getStopResults(BusSystem.JavaBusService.getStopResultsRequest request) {
            return base.Channel.getStopResults(request);
        }
        
        public BusSystem.JavaBusService.busStopSearchResult[] getStopResults(int stopID) {
            BusSystem.JavaBusService.getStopResultsRequest inValue = new BusSystem.JavaBusService.getStopResultsRequest();
            inValue.stopID = stopID;
            BusSystem.JavaBusService.getStopResultsResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).getStopResults(inValue);
            return retVal.results;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.getStopResultsResponse> BusSystem.JavaBusService.DataBase1.getStopResultsAsync(BusSystem.JavaBusService.getStopResultsRequest request) {
            return base.Channel.getStopResultsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.getStopResultsResponse> getStopResultsAsync(int stopID) {
            BusSystem.JavaBusService.getStopResultsRequest inValue = new BusSystem.JavaBusService.getStopResultsRequest();
            inValue.stopID = stopID;
            return ((BusSystem.JavaBusService.DataBase1)(this)).getStopResultsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.incrementRunStopResponse BusSystem.JavaBusService.DataBase1.incrementRunStop(BusSystem.JavaBusService.incrementRunStopRequest request) {
            return base.Channel.incrementRunStop(request);
        }
        
        public bool incrementRunStop(int runID) {
            BusSystem.JavaBusService.incrementRunStopRequest inValue = new BusSystem.JavaBusService.incrementRunStopRequest();
            inValue.runID = runID;
            BusSystem.JavaBusService.incrementRunStopResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).incrementRunStop(inValue);
            return retVal.incremented;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.incrementRunStopResponse> BusSystem.JavaBusService.DataBase1.incrementRunStopAsync(BusSystem.JavaBusService.incrementRunStopRequest request) {
            return base.Channel.incrementRunStopAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.incrementRunStopResponse> incrementRunStopAsync(int runID) {
            BusSystem.JavaBusService.incrementRunStopRequest inValue = new BusSystem.JavaBusService.incrementRunStopRequest();
            inValue.runID = runID;
            return ((BusSystem.JavaBusService.DataBase1)(this)).incrementRunStopAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusSystem.JavaBusService.setLinesResponse BusSystem.JavaBusService.DataBase1.setLines(BusSystem.JavaBusService.setLinesRequest request) {
            return base.Channel.setLines(request);
        }
        
        public void setLines(BusSystem.JavaBusService.line[] lines) {
            BusSystem.JavaBusService.setLinesRequest inValue = new BusSystem.JavaBusService.setLinesRequest();
            inValue.lines = lines;
            BusSystem.JavaBusService.setLinesResponse retVal = ((BusSystem.JavaBusService.DataBase1)(this)).setLines(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusSystem.JavaBusService.setLinesResponse> BusSystem.JavaBusService.DataBase1.setLinesAsync(BusSystem.JavaBusService.setLinesRequest request) {
            return base.Channel.setLinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusSystem.JavaBusService.setLinesResponse> setLinesAsync(BusSystem.JavaBusService.line[] lines) {
            BusSystem.JavaBusService.setLinesRequest inValue = new BusSystem.JavaBusService.setLinesRequest();
            inValue.lines = lines;
            return ((BusSystem.JavaBusService.DataBase1)(this)).setLinesAsync(inValue);
        }
    }
}
