
package eu.kniedzwiecki.integracja.books;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookManager", targetNamespace = "http://books.integracja.kniedzwiecki.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookManager {


    /**
     * 
     * @param bookIsbn
     * @return
     *     returns eu.kniedzwiecki.integracja.books.Book
     */
    @WebMethod
    @WebResult(name = "matched_book", targetNamespace = "")
    @RequestWrapper(localName = "searchByIsbn", targetNamespace = "http://books.integracja.kniedzwiecki.eu/", className = "eu.kniedzwiecki.integracja.books.SearchByIsbn")
    @ResponseWrapper(localName = "searchByIsbnResponse", targetNamespace = "http://books.integracja.kniedzwiecki.eu/", className = "eu.kniedzwiecki.integracja.books.SearchByIsbnResponse")
    @Action(input = "http://books.integracja.kniedzwiecki.eu/BookManager/searchByIsbnRequest", output = "http://books.integracja.kniedzwiecki.eu/BookManager/searchByIsbnResponse")
    public Book searchByIsbn(
        @WebParam(name = "book_isbn", targetNamespace = "")
        String bookIsbn);

    /**
     * 
     * @param bookAuthor
     * @return
     *     returns java.util.List<eu.kniedzwiecki.integracja.books.Book>
     */
    @WebMethod
    @WebResult(name = "matched_books", targetNamespace = "")
    @RequestWrapper(localName = "searchByAuthor", targetNamespace = "http://books.integracja.kniedzwiecki.eu/", className = "eu.kniedzwiecki.integracja.books.SearchByAuthor")
    @ResponseWrapper(localName = "searchByAuthorResponse", targetNamespace = "http://books.integracja.kniedzwiecki.eu/", className = "eu.kniedzwiecki.integracja.books.SearchByAuthorResponse")
    @Action(input = "http://books.integracja.kniedzwiecki.eu/BookManager/searchByAuthorRequest", output = "http://books.integracja.kniedzwiecki.eu/BookManager/searchByAuthorResponse")
    public List<Book> searchByAuthor(
        @WebParam(name = "book_author", targetNamespace = "")
        String bookAuthor);

    /**
     * 
     * @return
     *     returns java.util.List<eu.kniedzwiecki.integracja.books.Book>
     */
    @WebMethod
    @WebResult(name = "book", targetNamespace = "")
    @RequestWrapper(localName = "getBooks", targetNamespace = "http://books.integracja.kniedzwiecki.eu/", className = "eu.kniedzwiecki.integracja.books.GetBooks")
    @ResponseWrapper(localName = "getBooksResponse", targetNamespace = "http://books.integracja.kniedzwiecki.eu/", className = "eu.kniedzwiecki.integracja.books.GetBooksResponse")
    @Action(input = "http://books.integracja.kniedzwiecki.eu/BookManager/getBooksRequest", output = "http://books.integracja.kniedzwiecki.eu/BookManager/getBooksResponse")
    public List<Book> getBooks();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setBooks", targetNamespace = "http://books.integracja.kniedzwiecki.eu/", className = "eu.kniedzwiecki.integracja.books.SetBooks")
    @ResponseWrapper(localName = "setBooksResponse", targetNamespace = "http://books.integracja.kniedzwiecki.eu/", className = "eu.kniedzwiecki.integracja.books.SetBooksResponse")
    @Action(input = "http://books.integracja.kniedzwiecki.eu/BookManager/setBooksRequest", output = "http://books.integracja.kniedzwiecki.eu/BookManager/setBooksResponse")
    public void setBooks(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Book> arg0);

    /**
     * 
     * @param bookTitle
     * @return
     *     returns java.util.List<eu.kniedzwiecki.integracja.books.Book>
     */
    @WebMethod
    @WebResult(name = "matched_books", targetNamespace = "")
    @RequestWrapper(localName = "searchByTitle", targetNamespace = "http://books.integracja.kniedzwiecki.eu/", className = "eu.kniedzwiecki.integracja.books.SearchByTitle")
    @ResponseWrapper(localName = "searchByTitleResponse", targetNamespace = "http://books.integracja.kniedzwiecki.eu/", className = "eu.kniedzwiecki.integracja.books.SearchByTitleResponse")
    @Action(input = "http://books.integracja.kniedzwiecki.eu/BookManager/searchByTitleRequest", output = "http://books.integracja.kniedzwiecki.eu/BookManager/searchByTitleResponse")
    public List<Book> searchByTitle(
        @WebParam(name = "book_title", targetNamespace = "")
        String bookTitle);

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addBook", targetNamespace = "http://books.integracja.kniedzwiecki.eu/", className = "eu.kniedzwiecki.integracja.books.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://books.integracja.kniedzwiecki.eu/", className = "eu.kniedzwiecki.integracja.books.AddBookResponse")
    @Action(input = "http://books.integracja.kniedzwiecki.eu/BookManager/addBookRequest", output = "http://books.integracja.kniedzwiecki.eu/BookManager/addBookResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://books.integracja.kniedzwiecki.eu/BookManager/addBook/Fault/Exception")
    })
    public void addBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0)
        throws Exception_Exception
    ;

}
