//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integracja_klient.JavaBooksService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://books.integracja.kniedzwiecki.eu/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://books.integracja.kniedzwiecki.eu/")]
    public partial class book : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authorField;
        
        private string isbnField;
        
        private int pagesField;
        
        private bool pagesFieldSpecified;
        
        private string publisherField;
        
        private string titleField;
        
        private int yearField;
        
        private bool yearFieldSpecified;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("author");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                this.isbnField = value;
                this.RaisePropertyChanged("isbn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
                this.RaisePropertyChanged("pages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pagesSpecified {
            get {
                return this.pagesFieldSpecified;
            }
            set {
                this.pagesFieldSpecified = value;
                this.RaisePropertyChanged("pagesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string publisher {
            get {
                return this.publisherField;
            }
            set {
                this.publisherField = value;
                this.RaisePropertyChanged("publisher");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearSpecified {
            get {
                return this.yearFieldSpecified;
            }
            set {
                this.yearFieldSpecified = value;
                this.RaisePropertyChanged("yearSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://books.integracja.kniedzwiecki.eu/", ConfigurationName="JavaBooksService.BookManager")]
    public interface BookManager {
        
        // CODEGEN: Parameter 'matched_books' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://books.integracja.kniedzwiecki.eu/BookManager/searchByAuthorRequest", ReplyAction="http://books.integracja.kniedzwiecki.eu/BookManager/searchByAuthorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="matched_books")]
        integracja_klient.JavaBooksService.searchByAuthorResponse searchByAuthor(integracja_klient.JavaBooksService.searchByAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://books.integracja.kniedzwiecki.eu/BookManager/searchByAuthorRequest", ReplyAction="http://books.integracja.kniedzwiecki.eu/BookManager/searchByAuthorResponse")]
        System.Threading.Tasks.Task<integracja_klient.JavaBooksService.searchByAuthorResponse> searchByAuthorAsync(integracja_klient.JavaBooksService.searchByAuthorRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://books.integracja.kniedzwiecki.eu/BookManager/setBooksRequest", ReplyAction="http://books.integracja.kniedzwiecki.eu/BookManager/setBooksResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        integracja_klient.JavaBooksService.setBooksResponse setBooks(integracja_klient.JavaBooksService.setBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://books.integracja.kniedzwiecki.eu/BookManager/setBooksRequest", ReplyAction="http://books.integracja.kniedzwiecki.eu/BookManager/setBooksResponse")]
        System.Threading.Tasks.Task<integracja_klient.JavaBooksService.setBooksResponse> setBooksAsync(integracja_klient.JavaBooksService.setBooksRequest request);
        
        // CODEGEN: Parameter 'matched_books' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://books.integracja.kniedzwiecki.eu/BookManager/searchByTitleRequest", ReplyAction="http://books.integracja.kniedzwiecki.eu/BookManager/searchByTitleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="matched_books")]
        integracja_klient.JavaBooksService.searchByTitleResponse searchByTitle(integracja_klient.JavaBooksService.searchByTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://books.integracja.kniedzwiecki.eu/BookManager/searchByTitleRequest", ReplyAction="http://books.integracja.kniedzwiecki.eu/BookManager/searchByTitleResponse")]
        System.Threading.Tasks.Task<integracja_klient.JavaBooksService.searchByTitleResponse> searchByTitleAsync(integracja_klient.JavaBooksService.searchByTitleRequest request);
        
        // CODEGEN: Parameter 'book' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://books.integracja.kniedzwiecki.eu/BookManager/getBooksRequest", ReplyAction="http://books.integracja.kniedzwiecki.eu/BookManager/getBooksResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="book")]
        integracja_klient.JavaBooksService.getBooksResponse getBooks(integracja_klient.JavaBooksService.getBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://books.integracja.kniedzwiecki.eu/BookManager/getBooksRequest", ReplyAction="http://books.integracja.kniedzwiecki.eu/BookManager/getBooksResponse")]
        System.Threading.Tasks.Task<integracja_klient.JavaBooksService.getBooksResponse> getBooksAsync(integracja_klient.JavaBooksService.getBooksRequest request);
        
        // CODEGEN: Parameter 'matched_book' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://books.integracja.kniedzwiecki.eu/BookManager/searchByIsbnRequest", ReplyAction="http://books.integracja.kniedzwiecki.eu/BookManager/searchByIsbnResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="matched_book")]
        integracja_klient.JavaBooksService.searchByIsbnResponse searchByIsbn(integracja_klient.JavaBooksService.searchByIsbnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://books.integracja.kniedzwiecki.eu/BookManager/searchByIsbnRequest", ReplyAction="http://books.integracja.kniedzwiecki.eu/BookManager/searchByIsbnResponse")]
        System.Threading.Tasks.Task<integracja_klient.JavaBooksService.searchByIsbnResponse> searchByIsbnAsync(integracja_klient.JavaBooksService.searchByIsbnRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://books.integracja.kniedzwiecki.eu/BookManager/addBookRequest", ReplyAction="http://books.integracja.kniedzwiecki.eu/BookManager/addBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(integracja_klient.JavaBooksService.Exception), Action="http://books.integracja.kniedzwiecki.eu/BookManager/addBook/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        integracja_klient.JavaBooksService.addBookResponse addBook(integracja_klient.JavaBooksService.addBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://books.integracja.kniedzwiecki.eu/BookManager/addBookRequest", ReplyAction="http://books.integracja.kniedzwiecki.eu/BookManager/addBookResponse")]
        System.Threading.Tasks.Task<integracja_klient.JavaBooksService.addBookResponse> addBookAsync(integracja_klient.JavaBooksService.addBookRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByAuthor", WrapperNamespace="http://books.integracja.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class searchByAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books.integracja.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string book_author;
        
        public searchByAuthorRequest() {
        }
        
        public searchByAuthorRequest(string book_author) {
            this.book_author = book_author;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByAuthorResponse", WrapperNamespace="http://books.integracja.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class searchByAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books.integracja.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("matched_books", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public integracja_klient.JavaBooksService.book[] matched_books;
        
        public searchByAuthorResponse() {
        }
        
        public searchByAuthorResponse(integracja_klient.JavaBooksService.book[] matched_books) {
            this.matched_books = matched_books;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setBooks", WrapperNamespace="http://books.integracja.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class setBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books.integracja.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public integracja_klient.JavaBooksService.book[] arg0;
        
        public setBooksRequest() {
        }
        
        public setBooksRequest(integracja_klient.JavaBooksService.book[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setBooksResponse", WrapperNamespace="http://books.integracja.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class setBooksResponse {
        
        public setBooksResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByTitle", WrapperNamespace="http://books.integracja.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class searchByTitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books.integracja.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string book_title;
        
        public searchByTitleRequest() {
        }
        
        public searchByTitleRequest(string book_title) {
            this.book_title = book_title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByTitleResponse", WrapperNamespace="http://books.integracja.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class searchByTitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books.integracja.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("matched_books", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public integracja_klient.JavaBooksService.book[] matched_books;
        
        public searchByTitleResponse() {
        }
        
        public searchByTitleResponse(integracja_klient.JavaBooksService.book[] matched_books) {
            this.matched_books = matched_books;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBooks", WrapperNamespace="http://books.integracja.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getBooksRequest {
        
        public getBooksRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBooksResponse", WrapperNamespace="http://books.integracja.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class getBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books.integracja.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("book", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public integracja_klient.JavaBooksService.book[] book;
        
        public getBooksResponse() {
        }
        
        public getBooksResponse(integracja_klient.JavaBooksService.book[] book) {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByIsbn", WrapperNamespace="http://books.integracja.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class searchByIsbnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books.integracja.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string book_isbn;
        
        public searchByIsbnRequest() {
        }
        
        public searchByIsbnRequest(string book_isbn) {
            this.book_isbn = book_isbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByIsbnResponse", WrapperNamespace="http://books.integracja.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class searchByIsbnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books.integracja.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public integracja_klient.JavaBooksService.book matched_book;
        
        public searchByIsbnResponse() {
        }
        
        public searchByIsbnResponse(integracja_klient.JavaBooksService.book matched_book) {
            this.matched_book = matched_book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addBook", WrapperNamespace="http://books.integracja.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class addBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books.integracja.kniedzwiecki.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public integracja_klient.JavaBooksService.book arg0;
        
        public addBookRequest() {
        }
        
        public addBookRequest(integracja_klient.JavaBooksService.book arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addBookResponse", WrapperNamespace="http://books.integracja.kniedzwiecki.eu/", IsWrapped=true)]
    public partial class addBookResponse {
        
        public addBookResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookManagerChannel : integracja_klient.JavaBooksService.BookManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookManagerClient : System.ServiceModel.ClientBase<integracja_klient.JavaBooksService.BookManager>, integracja_klient.JavaBooksService.BookManager {
        
        public BookManagerClient() {
        }
        
        public BookManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        integracja_klient.JavaBooksService.searchByAuthorResponse integracja_klient.JavaBooksService.BookManager.searchByAuthor(integracja_klient.JavaBooksService.searchByAuthorRequest request) {
            return base.Channel.searchByAuthor(request);
        }
        
        public integracja_klient.JavaBooksService.book[] searchByAuthor(string book_author) {
            integracja_klient.JavaBooksService.searchByAuthorRequest inValue = new integracja_klient.JavaBooksService.searchByAuthorRequest();
            inValue.book_author = book_author;
            integracja_klient.JavaBooksService.searchByAuthorResponse retVal = ((integracja_klient.JavaBooksService.BookManager)(this)).searchByAuthor(inValue);
            return retVal.matched_books;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<integracja_klient.JavaBooksService.searchByAuthorResponse> integracja_klient.JavaBooksService.BookManager.searchByAuthorAsync(integracja_klient.JavaBooksService.searchByAuthorRequest request) {
            return base.Channel.searchByAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<integracja_klient.JavaBooksService.searchByAuthorResponse> searchByAuthorAsync(string book_author) {
            integracja_klient.JavaBooksService.searchByAuthorRequest inValue = new integracja_klient.JavaBooksService.searchByAuthorRequest();
            inValue.book_author = book_author;
            return ((integracja_klient.JavaBooksService.BookManager)(this)).searchByAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        integracja_klient.JavaBooksService.setBooksResponse integracja_klient.JavaBooksService.BookManager.setBooks(integracja_klient.JavaBooksService.setBooksRequest request) {
            return base.Channel.setBooks(request);
        }
        
        public void setBooks(integracja_klient.JavaBooksService.book[] arg0) {
            integracja_klient.JavaBooksService.setBooksRequest inValue = new integracja_klient.JavaBooksService.setBooksRequest();
            inValue.arg0 = arg0;
            integracja_klient.JavaBooksService.setBooksResponse retVal = ((integracja_klient.JavaBooksService.BookManager)(this)).setBooks(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<integracja_klient.JavaBooksService.setBooksResponse> integracja_klient.JavaBooksService.BookManager.setBooksAsync(integracja_klient.JavaBooksService.setBooksRequest request) {
            return base.Channel.setBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<integracja_klient.JavaBooksService.setBooksResponse> setBooksAsync(integracja_klient.JavaBooksService.book[] arg0) {
            integracja_klient.JavaBooksService.setBooksRequest inValue = new integracja_klient.JavaBooksService.setBooksRequest();
            inValue.arg0 = arg0;
            return ((integracja_klient.JavaBooksService.BookManager)(this)).setBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        integracja_klient.JavaBooksService.searchByTitleResponse integracja_klient.JavaBooksService.BookManager.searchByTitle(integracja_klient.JavaBooksService.searchByTitleRequest request) {
            return base.Channel.searchByTitle(request);
        }
        
        public integracja_klient.JavaBooksService.book[] searchByTitle(string book_title) {
            integracja_klient.JavaBooksService.searchByTitleRequest inValue = new integracja_klient.JavaBooksService.searchByTitleRequest();
            inValue.book_title = book_title;
            integracja_klient.JavaBooksService.searchByTitleResponse retVal = ((integracja_klient.JavaBooksService.BookManager)(this)).searchByTitle(inValue);
            return retVal.matched_books;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<integracja_klient.JavaBooksService.searchByTitleResponse> integracja_klient.JavaBooksService.BookManager.searchByTitleAsync(integracja_klient.JavaBooksService.searchByTitleRequest request) {
            return base.Channel.searchByTitleAsync(request);
        }
        
        public System.Threading.Tasks.Task<integracja_klient.JavaBooksService.searchByTitleResponse> searchByTitleAsync(string book_title) {
            integracja_klient.JavaBooksService.searchByTitleRequest inValue = new integracja_klient.JavaBooksService.searchByTitleRequest();
            inValue.book_title = book_title;
            return ((integracja_klient.JavaBooksService.BookManager)(this)).searchByTitleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        integracja_klient.JavaBooksService.getBooksResponse integracja_klient.JavaBooksService.BookManager.getBooks(integracja_klient.JavaBooksService.getBooksRequest request) {
            return base.Channel.getBooks(request);
        }
        
        public integracja_klient.JavaBooksService.book[] getBooks() {
            integracja_klient.JavaBooksService.getBooksRequest inValue = new integracja_klient.JavaBooksService.getBooksRequest();
            integracja_klient.JavaBooksService.getBooksResponse retVal = ((integracja_klient.JavaBooksService.BookManager)(this)).getBooks(inValue);
            return retVal.book;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<integracja_klient.JavaBooksService.getBooksResponse> integracja_klient.JavaBooksService.BookManager.getBooksAsync(integracja_klient.JavaBooksService.getBooksRequest request) {
            return base.Channel.getBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<integracja_klient.JavaBooksService.getBooksResponse> getBooksAsync() {
            integracja_klient.JavaBooksService.getBooksRequest inValue = new integracja_klient.JavaBooksService.getBooksRequest();
            return ((integracja_klient.JavaBooksService.BookManager)(this)).getBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        integracja_klient.JavaBooksService.searchByIsbnResponse integracja_klient.JavaBooksService.BookManager.searchByIsbn(integracja_klient.JavaBooksService.searchByIsbnRequest request) {
            return base.Channel.searchByIsbn(request);
        }
        
        public integracja_klient.JavaBooksService.book searchByIsbn(string book_isbn) {
            integracja_klient.JavaBooksService.searchByIsbnRequest inValue = new integracja_klient.JavaBooksService.searchByIsbnRequest();
            inValue.book_isbn = book_isbn;
            integracja_klient.JavaBooksService.searchByIsbnResponse retVal = ((integracja_klient.JavaBooksService.BookManager)(this)).searchByIsbn(inValue);
            return retVal.matched_book;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<integracja_klient.JavaBooksService.searchByIsbnResponse> integracja_klient.JavaBooksService.BookManager.searchByIsbnAsync(integracja_klient.JavaBooksService.searchByIsbnRequest request) {
            return base.Channel.searchByIsbnAsync(request);
        }
        
        public System.Threading.Tasks.Task<integracja_klient.JavaBooksService.searchByIsbnResponse> searchByIsbnAsync(string book_isbn) {
            integracja_klient.JavaBooksService.searchByIsbnRequest inValue = new integracja_klient.JavaBooksService.searchByIsbnRequest();
            inValue.book_isbn = book_isbn;
            return ((integracja_klient.JavaBooksService.BookManager)(this)).searchByIsbnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        integracja_klient.JavaBooksService.addBookResponse integracja_klient.JavaBooksService.BookManager.addBook(integracja_klient.JavaBooksService.addBookRequest request) {
            return base.Channel.addBook(request);
        }
        
        public void addBook(integracja_klient.JavaBooksService.book arg0) {
            integracja_klient.JavaBooksService.addBookRequest inValue = new integracja_klient.JavaBooksService.addBookRequest();
            inValue.arg0 = arg0;
            integracja_klient.JavaBooksService.addBookResponse retVal = ((integracja_klient.JavaBooksService.BookManager)(this)).addBook(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<integracja_klient.JavaBooksService.addBookResponse> integracja_klient.JavaBooksService.BookManager.addBookAsync(integracja_klient.JavaBooksService.addBookRequest request) {
            return base.Channel.addBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<integracja_klient.JavaBooksService.addBookResponse> addBookAsync(integracja_klient.JavaBooksService.book arg0) {
            integracja_klient.JavaBooksService.addBookRequest inValue = new integracja_klient.JavaBooksService.addBookRequest();
            inValue.arg0 = arg0;
            return ((integracja_klient.JavaBooksService.BookManager)(this)).addBookAsync(inValue);
        }
    }
}
